// Generates src/styles/tokens.css from design/tokens.json (the design system's tokens, copied verbatim).
// Light values on :root, dark values on [data-theme="dark"]. Do not edit token values here or in the output.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'design/tokens.json'), 'utf8'));
const light = [];
const dark = [];
const families = ['color', 'shadow', 'spacing', 'radius', 'blur', 'size'];
for (const fam of families) {
    for (const t of tokens[fam]?.tokens ?? []) {
        const v = t.value;
        if (typeof v === 'string' || typeof v === 'number') {
            light.push(`  --${t.name}: ${v};`);
            continue;
        }
        if (t.name.startsWith('photo-')) continue; // retired with the photo ground (prototype rule)
        if (v.light !== undefined) light.push(`  --${t.name}: ${v.light};`);
        if (v.dark !== undefined) dark.push(`  --${t.name}: ${v.dark};`);
    }
}
const out = `/* GENERATED by scripts/gen-tokens.mjs from design/tokens.json. Do not edit. */
:root {
${light.join('\n')}
  color-scheme: light;
}
[data-theme="dark"] {
${dark.join('\n')}
  color-scheme: dark;
}
`;
mkdirSync(resolve(root, 'src/styles'), { recursive: true });
writeFileSync(resolve(root, 'src/styles/tokens.css'), out);
console.log(`tokens.css: ${light.length} light, ${dark.length} dark variables`);
