/* STRINGS added for the prototype screens. [EN, TL, HIL].
   EN is complete. TL and HIL are DRAFTS. Draft: needs native review before any farmer, driver or judge reads them
   as final. Title Case for labels (CSS uppercases), sentence case for sentences. */
export const PROTOTYPE_STRINGS: Record<string, [string, string, string]> = {
    // chrome
    'theme.dark': ['Dark', 'Madilim', 'Madulom'],
    'theme.light': ['Light', 'Maliwanag', 'Masanag'],
    'role.coordinator': ['Coordinator · Cluster 1', 'Coordinator · Cluster 1', 'Coordinator · Cluster 1'],
    'role.buyer': ['Buyer (simulated)', 'Mamimili (simulated)', 'Bumalakal (simulated)'],
    'role.driver': ['Driver (simulated)', 'Driver (simulated)', 'Driver (simulated)'],
    'unit.sacks': ['sacks', 'sako', 'sako'],
    // components
    'market.filled': ['Filled', 'Napunan', 'Napuno'],
    'market.filledof': ['{filled} of {tonnes} t filled · {pct}%', '{filled} sa {tonnes} t napunan · {pct}%', '{filled} sa {tonnes} t napuno · {pct}%'],
    'cal.total': ['Total', 'Kabuuan', 'Kabilugan'],
    'cal.farms': ['{n} farms', '{n} bukid', '{n} ka uma'],
    'driver.away': ['{km} km away', '{km} km ang layo', '{km} km ang kalayuon'],
    // farm list + profile
    'farm.list': ['Cluster 1 Farms', 'Mga Bukid ng Cluster 1', 'Mga Uma sang Cluster 1'],
    'farm.search': ['Search Farms', 'Maghanap ng Bukid', 'Mangita sang Uma'],
    'farm.summary': ['{n} farms · {ha} ha', '{n} bukid · {ha} ha', '{n} ka uma · {ha} ha'],
    'farm.open': ['Open {id}', 'Buksan ang {id}', 'Buksan ang {id}'],
    'farm.back': ['All Farms', 'Lahat ng Bukid', 'Tanan nga Uma'],
    'farm.harvest': ['Harvest', 'Ani', 'Alani'],
    'farm.harvestLine': ['{week} · {date}', '{week} · {date}', '{week} · {date}'],
    'farm.forecast': ['Forecast, Dried', 'Tantiya, Tuyo', 'Banta, Uga'],
    'farm.lot': ['Lot', 'Lot', 'Lot'],
    'farm.viewPlan': ['View in Plan', 'Tingnan sa Plano', 'Tan-awa sa Plano'],
    // plan
    'plan.eyebrow': ['Cluster 1 · {barangays} · W1-W4 from {start}', 'Cluster 1 · {barangays} · W1-W4 mula {start}', 'Cluster 1 · {barangays} · W1-W4 halin {start}'],
    'plan.note.farms': ['{b} barangays · {split} farms', '{b} barangay · {split} bukid', '{b} ka barangay · {split} ka uma'],
    'plan.note.area': ['Average {avg} ha per farm', 'Karaniwang {avg} ha bawat bukid', 'Average {avg} ha kada uma'],
    'plan.note.tonnes': ['Dried. Wet {wet} t at {yield} kg/ha, {loss}% loss, x{factor}', 'Tuyo. Basa {wet} t sa {yield} kg/ha, {loss}% lugi, x{factor}', 'Uga. Basa {wet} t sa {yield} kg/ha, {loss}% kapierdi, x{factor}'],
    'plan.note.peak': ['{t} t dried · book dryer slots early', '{t} t tuyo · mag-book ng patuyuan nang maaga', '{t} t uga · mag-book sang pamalahan sing temprano'],
    'plan.caption': ['Dried palay tonnes by barangay and harvest week (forecast)', 'Toneladang tuyong palay ayon sa barangay at linggo ng ani (tantiya)', 'Tonelada sang uga nga palay suno sa barangay kag semana sang alani (banta)'],
    'plan.legend': ['Bars: dried tonnes per week. Gold outline: Farm {farm}, Lot {lot}.', 'Bar: toneladang tuyo bawat linggo. Gintong guhit: Bukid {farm}, Lot {lot}.', 'Bar: tonelada nga uga kada semana. Bulawan nga linya: Uma {farm}, Lot {lot}.'],
    // market
    'market.eyebrow': ['Buyers post standing orders · the cluster fills them', 'Nagpo-post ng order ang mamimili · pinupunan ng cluster', 'Nagapost sang order ang bumalakal · ginapun-an sang cluster'],
    'market.filters': ['Filter Commitments', 'I-filter ang Pangako', 'I-filter ang Saad'],
    'market.group.grade': ['Grade', 'Grado', 'Grado'],
    'market.group.volume': ['Volume', 'Dami', 'Kadamuon'],
    'market.group.window': ['Window', 'Panahon', 'Tion'],
    'market.assumed': ['{id}: grade, MC and price assumed (not in the brief)', '{id}: grado, MC at presyo ay tantiya lamang', '{id}: grado, MC kag presyo banta lang'],
    'market.lotline': ['Dried · {grade} · {mc} · {week}', 'Tuyo · {grade} · {mc} · {week}', 'Uga · {grade} · {mc} · {week}'],
    'market.fills': ['Matched to {id}: {filled} t of {tonnes} t across {n} lots, including {lot}.', 'Itinugma sa {id}: {filled} t sa {tonnes} t mula sa {n} lot, kasama ang {lot}.', 'Gin-tupong sa {id}: {filled} t sa {tonnes} t halin sa {n} ka lot, upod ang {lot}.'],
    'market.committed': ['Committed to {id}', 'Naipangako sa {id}', 'Nasaad sa {id}'],
    'market.forecast.title': ['Auto-Match to Forecast', 'Auto-Match sa Tantiya', 'Auto-Match sa Banta'],
    'market.col.commitment': ['Commitment', 'Pangako', 'Saad'],
    'market.col.requested': ['Requested', 'Hiniling', 'Ginpangayo'],
    'market.col.forecast': ['Forecast in Window', 'Tantiya sa Panahon', 'Banta sa Tion'],
    'market.col.matched': ['Matched', 'Tugma', 'Nagtupong'],
    'market.col.lots': ['Lots', 'Lot', 'Lot'],
    // dry
    'dry.eyebrow': ['{dryer} · {place}', '{dryer} · {place}', '{dryer} · {place}'],
    'dry.note.capacity': ['{t} t per day (assumed)', '{t} t bawat araw (tantiya)', '{t} t kada adlaw (banta)'],
    'dry.note.booked': ['{pct}% of {cap} this week', '{pct}% ng {cap} ngayong linggo', '{pct}% sang {cap} subong nga semana'],
    'dry.hero.label': ['Lot {lot} Slot', 'Slot ng Lot {lot}', 'Slot sang Lot {lot}'],
    'dry.hero.note': ['{day} · {kg} kg · {sacks} sacks', '{day} · {kg} kg · {sacks} sako', '{day} · {kg} kg · {sacks} ka sako'],
    'dry.weeks': ['Harvest Week', 'Linggo ng Ani', 'Semana sang Alani'],
    'dry.rule': ['Each lot dries on its harvest day, or the next day with room. No day goes over {t} t.', 'Pinapatuyo ang bawat lot sa araw ng ani, o sa susunod na araw na may puwang. Walang araw na lalampas sa {t} t.', 'Ginapamala ang kada lot sa adlaw sang alani, ukon sa masunod nga adlaw nga may lugar. Wala sang adlaw nga molapaw sa {t} t.'],
};
