/* STRINGS added for the prototype screens. [EN, TL, HIL].
   EN is complete. TL and HIL are DRAFTS. Draft: needs native review before any farmer, driver or judge reads them
   as final. Title Case for labels (CSS uppercases), sentence case for sentences. */
export const PROTOTYPE_STRINGS: Record<string, [string, string, string]> = {
    // chrome
    'theme.dark': ['Dark', 'Madilim', 'Madulom'],
    'theme.light': ['Light', 'Maliwanag', 'Masanag'],
    'role.coordinator': ['Coordinator · Cluster 1', 'Coordinator · Cluster 1', 'Coordinator · Cluster 1'],
    'role.buyer': ['Buyer (simulated)', 'Mamimili (simulated)', 'Bumalakal (simulated)'],
    'role.driver': ['Driver (simulated)', 'Driver (simulated)', 'Driver (simulated)'],
    'unit.sacks': ['sacks', 'sako', 'sako'],
    // components
    'market.filled': ['Filled', 'Napunan', 'Napuno'],
    'market.filledof': ['{filled} of {tonnes} t filled · {pct}%', '{filled} sa {tonnes} t napunan · {pct}%', '{filled} sa {tonnes} t napuno · {pct}%'],
    'cal.total': ['Total', 'Kabuuan', 'Kabilugan'],
    'cal.farms': ['{n} farms', '{n} bukid', '{n} ka uma'],
    'driver.away': ['{km} km away', '{km} km ang layo', '{km} km ang kalayuon'],
    // farm list + profile
    'farm.list': ['Cluster 1 Farms', 'Mga Bukid ng Cluster 1', 'Mga Uma sang Cluster 1'],
    'farm.search': ['Search Farms', 'Maghanap ng Bukid', 'Mangita sang Uma'],
    'farm.summary': ['{n} farms · {ha} ha', '{n} bukid · {ha} ha', '{n} ka uma · {ha} ha'],
    'farm.open': ['Open {id}', 'Buksan ang {id}', 'Buksan ang {id}'],
    'farm.back': ['All Farms', 'Lahat ng Bukid', 'Tanan nga Uma'],
    'farm.harvest': ['Harvest', 'Ani', 'Alani'],
    'farm.harvestLine': ['{week} · {date}', '{week} · {date}', '{week} · {date}'],
    'farm.forecast': ['Forecast, Dried', 'Tantiya, Tuyo', 'Banta, Uga'],
    'farm.lot': ['Lot', 'Lot', 'Lot'],
    'farm.viewPlan': ['View in Plan', 'Tingnan sa Plano', 'Tan-awa sa Plano'],
    // plan
    'plan.eyebrow': ['Cluster 1 · {barangays} · W1-W4 from {start}', 'Cluster 1 · {barangays} · W1-W4 mula {start}', 'Cluster 1 · {barangays} · W1-W4 halin {start}'],
    'plan.note.farms': ['{b} barangays · {split} farms', '{b} barangay · {split} bukid', '{b} ka barangay · {split} ka uma'],
    'plan.note.area': ['Average {avg} ha per farm', 'Karaniwang {avg} ha bawat bukid', 'Average {avg} ha kada uma'],
    'plan.note.tonnes': ['Dried. Wet {wet} t at {yield} kg/ha, {loss}% loss, x{factor}', 'Tuyo. Basa {wet} t sa {yield} kg/ha, {loss}% lugi, x{factor}', 'Uga. Basa {wet} t sa {yield} kg/ha, {loss}% kapierdi, x{factor}'],
    'plan.note.peak': ['{t} t dried · book dryer slots early', '{t} t tuyo · mag-book ng patuyuan nang maaga', '{t} t uga · mag-book sang pamalahan sing temprano'],
    'plan.caption': ['Dried palay tonnes by barangay and harvest week (forecast)', 'Toneladang tuyong palay ayon sa barangay at linggo ng ani (tantiya)', 'Tonelada sang uga nga palay suno sa barangay kag semana sang alani (banta)'],
    'plan.legend': ['Bars: dried tonnes per week. Gold outline: Farm {farm}, Lot {lot}.', 'Bar: toneladang tuyo bawat linggo. Gintong guhit: Bukid {farm}, Lot {lot}.', 'Bar: tonelada nga uga kada semana. Bulawan nga linya: Uma {farm}, Lot {lot}.'],
    // market
    'market.eyebrow': ['Buyers post standing orders · the cluster fills them', 'Nagpo-post ng order ang mamimili · pinupunan ng cluster', 'Nagapost sang order ang bumalakal · ginapun-an sang cluster'],
    'market.filters': ['Filter Commitments', 'I-filter ang Pangako', 'I-filter ang Saad'],
    'market.group.grade': ['Grade', 'Grado', 'Grado'],
    'market.group.volume': ['Volume', 'Dami', 'Kadamuon'],
    'market.group.window': ['Window', 'Panahon', 'Tion'],
    'market.assumed': ['{id}: grade, MC and price assumed (not in the brief)', '{id}: grado, MC at presyo ay tantiya lamang', '{id}: grado, MC kag presyo banta lang'],
    'market.lotline': ['Dried · {grade} · {mc} · {week}', 'Tuyo · {grade} · {mc} · {week}', 'Uga · {grade} · {mc} · {week}'],
    'market.fills': ['Matched to {id}: {filled} t of {tonnes} t across {n} lots, including {lot}.', 'Itinugma sa {id}: {filled} t sa {tonnes} t mula sa {n} lot, kasama ang {lot}.', 'Gin-tupong sa {id}: {filled} t sa {tonnes} t halin sa {n} ka lot, upod ang {lot}.'],
    'market.committed': ['Committed to {id}', 'Naipangako sa {id}', 'Nasaad sa {id}'],
    'market.forecast.title': ['Auto-Match to Forecast', 'Auto-Match sa Tantiya', 'Auto-Match sa Banta'],
    'market.col.commitment': ['Commitment', 'Pangako', 'Saad'],
    'market.col.requested': ['Requested', 'Hiniling', 'Ginpangayo'],
    'market.col.forecast': ['Forecast in Window', 'Tantiya sa Panahon', 'Banta sa Tion'],
    'market.col.matched': ['Matched', 'Tugma', 'Nagtupong'],
    'market.col.lots': ['Lots', 'Lot', 'Lot'],
    // dry
    'dry.eyebrow': ['{dryer} · {place}', '{dryer} · {place}', '{dryer} · {place}'],
    'dry.note.capacity': ['{t} t per day (assumed)', '{t} t bawat araw (tantiya)', '{t} t kada adlaw (banta)'],
    'dry.note.booked': ['{pct}% of {cap} this week', '{pct}% ng {cap} ngayong linggo', '{pct}% sang {cap} subong nga semana'],
    'dry.hero.label': ['Lot {lot} Slot', 'Slot ng Lot {lot}', 'Slot sang Lot {lot}'],
    'dry.hero.note': ['{day} · {kg} kg · {sacks} sacks', '{day} · {kg} kg · {sacks} sako', '{day} · {kg} kg · {sacks} ka sako'],
    'dry.weeks': ['Harvest Week', 'Linggo ng Ani', 'Semana sang Alani'],
    'dry.rule': ['Each lot dries on its harvest day, or the next day with room. No day goes over {t} t.', 'Pinapatuyo ang bawat lot sa araw ng ani, o sa susunod na araw na may puwang. Walang araw na lalampas sa {t} t.', 'Ginapamala ang kada lot sa adlaw sang alani, ukon sa masunod nga adlaw nga may lugar. Wala sang adlaw nga molapaw sa {t} t.'],
    // haul
    'haul.new': ['New Haul Request', 'Bagong Hiling na Hakot', 'Bag-o nga Pangayo nga Hakot'],
    'haul.route': ['Route', 'Ruta', 'Ruta'],
    'haul.sacks.help': ['Dried lot {lot}: {kg} kg = {n} sacks of {per} kg', 'Tuyong lot {lot}: {kg} kg = {n} sako na {per} kg', 'Uga nga lot {lot}: {kg} kg = {n} ka sako nga {per} kg'],
    'haul.waiting': ['Waiting for {driver} to accept', 'Hinihintay na tanggapin ni {driver}', 'Ginahulat nga batunon ni {driver}'],
    'haul.vehicles': ['Vehicle for {n} sacks', 'Sasakyan para sa {n} sako', 'Salakyan para sa {n} ka sako'],
    'haul.drivers': ['Pick Any Driver', 'Pumili ng Kahit Anong Driver', 'Magpili sang Bisan Sin-o nga Driver'],
    'haul.assign': ['Assign', 'Italaga', 'I-assign'],
    'haul.busy': ['Busy', 'Abala', 'Okupado'],
    'haul.free': ['Available', 'Bakante', 'Bakante'],
    'haul.trips': ['{n} trip(s) · {price}', '{n} biyahe · {price}', '{n} ka biyahe · {price}'],
    'haul.overridden': ['Coordinator override', 'Pinalitan ng coordinator', 'Ginbaylo sang coordinator'],
    'haul.close': ['Close List', 'Isara ang Listahan', 'Isira ang Listahan'],
    'haul.delivered': ['Mark Delivered', 'Markahang Naihatid', 'Markahan nga Naihatod'],
    'haul.declined': ['Job declined. The coordinator assigns the next nearest driver.', 'Tinanggihan ang trabaho. Itatalaga ng coordinator ang susunod na pinakamalapit na driver.', 'Wala ginbaton ang obra. I-assign sang coordinator ang masunod nga pinakamalapit nga driver.'],
    'haul.undo': ['Undo', 'Ibalik', 'Ibalik'],
    'haul.about': ['{n} (about {t} t dried)', '{n} (mga {t} t tuyo)', '{n} (mga {t} t uga)'],
    'haul.done': ['Delivered. Thank you!', 'Naihatid na. Salamat!', 'Naihatod na. Salamat!'],
    'haul.cost': ['Haul Cost', 'Gastos sa Hakot', 'Gasto sa Hakot'],
    // pay
    'pay.eyebrow': ['Orders · Pay', 'Mga Order · Bayad', 'Mga Order · Bayad'],
    'pay.eyebrow.lot': ['Orders · Pay · Lot {lot}', 'Mga Order · Bayad · Lot {lot}', 'Mga Order · Bayad · Lot {lot}'],
    'pay.list.title': ['Lots Matched to Commitments', 'Mga Lot na Itinugma sa Pangako', 'Mga Lot nga Gin-tupong sa Saad'],
    'pay.list.note': ['Only weighed lots settle. Forecast lots show an estimate from the same rates.', 'Ang natimbang na lot lang ang binabayaran. Tantiya ang ipinapakita sa iba, sa parehong rate.', 'Ang natimbang nga lot lang ang ginabayaran. Banta ang ginapakita sa iban, sa pareho nga rate.'],
    'pay.col.lot': ['Lot', 'Lot', 'Lot'],
    'pay.col.farm': ['Farm', 'Bukid', 'Uma'],
    'pay.col.commitment': ['Commitment', 'Pangako', 'Saad'],
    'pay.col.harvest': ['Harvest', 'Ani', 'Alani'],
    'pay.col.kg': ['Dried kg', 'Kg na Tuyo', 'Kg nga Uga'],
    'pay.col.net': ['Net to Farmer', 'Netong Matatanggap', 'Neto nga Mabaton'],
    'pay.col.status': ['Status', 'Katayuan', 'Kahimtangan'],
    'pay.weighed': ['Weighed', 'Natimbang', 'Natimbang'],
    'pay.estimate': ['Estimate', 'Tantiya', 'Banta'],
    'pay.open': ['Open Lot {lot}', 'Buksan ang Lot {lot}', 'Buksan ang Lot {lot}'],
    'pay.record': ['Lot Record', 'Talaan ng Lot', 'Rekord sang Lot'],
    'pay.rec.farm': ['Farm · Barangay', 'Bukid · Barangay', 'Uma · Barangay'],
    'pay.rec.harvest': ['Harvest', 'Ani', 'Alani'],
    'pay.rec.weight': ['Dried Weight', 'Timbang na Tuyo', 'Timbang nga Uga'],
    'pay.rec.quality': ['Grade · Moisture', 'Grado · Halumigmig', 'Grado · Kahalumigmigon'],
    'pay.rec.buyer': ['Commitment · Buyer', 'Pangako · Mamimili', 'Saad · Bumalakal'],
    'pay.rec.haul': ['Haul · Driver', 'Hakot · Driver', 'Hakot · Driver'],
    'pay.rec.slot': ['Dryer Slot', 'Slot sa Patuyuan', 'Slot sa Pamalahan'],
    'pay.rec.slip': ['Slip', 'Resibo', 'Resibo'],
    'pay.viewSms': ['View SMS', 'Tingnan ang SMS', 'Tan-awa ang SMS'],
    'pay.back': ['All Lots', 'Lahat ng Lot', 'Tanan nga Lot'],
    // sms
    'sms.all.title': ['SMS to Farmer · Lot {lot}', 'SMS sa Magsasaka · Lot {lot}', 'SMS sa Mangunguma · Lot {lot}'],
    'sms.ascii': ['Plain ASCII on purpose: every message stays GSM-7, so each one is a single 160-character SMS.', 'Sadyang plain ASCII: GSM-7 ang bawat mensahe, kaya isang 160-character na SMS lang ang bawat isa.', 'Tuyo nga plain ASCII: GSM-7 ang kada mensahe, gani isa lang ka 160-character nga SMS ang kada isa.'],
    'sms.all.link': ['All Three Languages', 'Lahat ng Tatlong Wika', 'Tanan nga Tatlo ka Lingguahe'],
    // demo
    'demo.beat.farm': ['Farm Profile', 'Profile ng Bukid', 'Profile sang Uma'],
    'demo.beat.plan': ['Harvest Plan', 'Plano ng Ani', 'Plano sang Alani'],
    'demo.beat.market': ['Market Match', 'Tugma sa Merkado', 'Tupong sa Merkado'],
    'demo.beat.dry': ['Dryer Slot', 'Slot sa Patuyuan', 'Slot sa Pamalahan'],
    'demo.beat.haul': ['Haul', 'Hakot', 'Hakot'],
    'demo.beat.pay': ['Settlement', 'Bayaran', 'Bayaran'],
    'demo.beat.sms': ['SMS to Farmer', 'SMS sa Magsasaka', 'SMS sa Mangunguma'],
    'demo.beat.end': ['End Card', 'Pangwakas', 'Pangtapos'],
    'demo.prev': ['Back', 'Bumalik', 'Balik'],
    'demo.next': ['Next', 'Susunod', 'Masunod'],
    'demo.play': ['Play', 'I-play', 'I-play'],
    'demo.pause': ['Pause', 'I-pause', 'I-pause'],
    'demo.restart': ['Restart', 'Ulitin', 'Liwaton'],
    'demo.keys': ['Arrows step · Space pauses · R restarts', 'Arrow: hakbang · Space: hinto · R: ulit', 'Arrow: lakat · Space: untat · R: liwat'],
    'demo.controls': ['Demo Controls', 'Kontrol ng Demo', 'Kontrol sang Demo'],
    'end.title': ['One cluster. One hundred farms. 80% paid within 24 hours.', 'Isang cluster. Sandaang bukid. 80% bayad sa loob ng 24 oras.', 'Isa ka cluster. Isa ka gatos nga uma. 80% bayad sa sulod sang 24 oras.'],
    // responsive shell + pagination (TL/HIL drafts: needs native review)
    'nav.more': ['More', 'Iba Pa', 'Iban Pa'],
    'sms.inbox': ["Farmer {farm}'s Phone · Messages", 'Telepono ng Magsasaka {farm} · Mga Mensahe', 'Telepono sang Mangunguma {farm} · Mga Mensahe'],
    'list.showing': ['Showing {from}-{to} of {total}', 'Ipinapakita ang {from}-{to} sa {total}', 'Ginapakita ang {from}-{to} sa {total}'],
    'list.prev': ['Previous', 'Nakaraan', 'Nauna'],
    'list.next': ['Next', 'Susunod', 'Masunod'],
    'list.pageOf': ['Page {n} of {total}', 'Pahina {n} sa {total}', 'Pahina {n} sa {total}'],
    'list.page': ['Page {n}', 'Pahina {n}', 'Pahina {n}'],
    'list.rowsPerPage': ['Rows per page', 'Hilera bawat pahina', 'Linya kada pahina'],
    'list.pagination': ['Pagination', 'Paglipat ng Pahina', 'Paglipat sang Pahina'],
    'list.filters': ['Filters', 'Mga Filter', 'Mga Filter'],
    'filter.allStatuses': ['All statuses', 'Lahat ng katayuan', 'Tanan nga kahimtangan'],
    'filter.allBarangays': ['All barangays', 'Lahat ng barangay', 'Tanan nga barangay'],
    'farm.noMatch': ['No farms match', 'Walang bukid na tugma', 'Wala sang uma nga nagtupong'],
};
